### POST request to example server
#POST http://localhost:5000/locale
#Content-Type: application/json
#
#{
#  "home_welcome": "Welcome to our website",
#  "about_us": "Learn more about us"
#}

#GET http://localhost:5000/locale
#Content-Type: application/json
####

POST http://localhost:5000/signup
Content-Type: application/json

{
  "email": "random@gmail.com",
  "password": "1234567890"
}


